### ISSUE TITLE
Ability to run nodes with different docker images

### ISSUE THREAD

**Issue by brandisimus** [oxheadalpha/tezos-k8s#113] opened 2021-02-17 16:17 UTC
A user should be able to chose a number of nodes running specific versions of protocols and simulate the a protocol upgrade.

**Comment by elric1** [comment] 2021-06-01 15:40
@nicolasochem has provided the ability to upgrade protocols. This requires an image that supports both protocols, but this is standard.
Do we want to be able to simulate a mixed network? I can easily add this my `name-the-nodes` branch. The branch lets you define new stateful sets which are named and fire up nodes in a configurable way. It would be easy enough to specify a different image for each statefulset if we think that would be useful? I think that it may very well be useful for testing upgrades when a certain percentage of the nodes haven't bothered to upgrade, e.g.

**Comment by harryttd** [comment] 2021-07-21 18:39
duplicate of #226

**Closed** 2021-09-15 15:14 UTC
